[env:waveshare_amoled_143]
;platform = espressif@3.1.1
platform = espressif32
framework = arduino
;board = waveshare_esp32_s3_touch_amoled_143
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600

board_build.arduino.memory_type = qio_opi
; added after changing board to devkitc
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.build_partitions = waveshare.csv
; end of add

;board.build_partitions = custom.csv

build_flags =
  -Iinclude
  -DLV_CONF_INCLUDE_SIMPLE
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue

lib_deps =
  moononournation/GFX Library for Arduino@^1.6.7
  ;bodmer/TFT_eSPI@^2.5.43
  fbiego/ESP32Time@^2.0.6
  lewisxhe/XPowersLib@^0.3.3
  lvgl/lvgl@8.4.0

; [env:esp32-s3-devkitc-1]
; platform = espressif32
; board = esp32-s3-devkitc-1
; framework = arduino

; board_build.arduino.memory_type = qio_opi
; board_build.flash_mode = qio
; board_build.psram_type = opi
; board_upload.flash_size = 16MB
; board_upload.maximum_size = 16777216
; board_build.partitions = default_16MB.csv
; board_build.extra_flags = 
;   -DBOARD_HAS_PSRAM
;   -DARDUINO_USB_CDC_ON_BOOT=1
; monitor_speed = 115200
